/* (c) Magnus Auvinen. See licence.txt in the root of the distribution for more information. */
/* If you are missing that file, acquire a complete release at teeworlds.com.                */
#ifndef GAME_VARIABLES_H
#define GAME_VARIABLES_H
#undef GAME_VARIABLES_H // this file will be included several times


// client
MACRO_CONFIG_INT(ClPredict, cl_predict, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Predict client movements")
MACRO_CONFIG_INT(ClNameplates, cl_nameplates, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Show name plates")
MACRO_CONFIG_INT(ClNameplatesAlways, cl_nameplates_always, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Always show name plates disregarding of distance")
MACRO_CONFIG_INT(ClNameplatesTeamcolors, cl_nameplates_teamcolors, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Use team colors for name plates")
MACRO_CONFIG_INT(ClNameplatesSize, cl_nameplates_size, 50, 0, 100, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Size of the name plates from 0 to 100%")
MACRO_CONFIG_INT(ClAutoswitchWeapons, cl_autoswitch_weapons, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Auto switch weapon on pickup")

MACRO_CONFIG_INT(ClShowhud, cl_showhud, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Show ingame HUD")
MACRO_CONFIG_INT(ClShowfps, cl_showfps, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Show ingame FPS counter")

MACRO_CONFIG_INT(ClAirjumpindicator, cl_airjumpindicator, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")
MACRO_CONFIG_INT(ClThreadsoundloading, cl_threadsoundloading, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Load sound files threaded")

MACRO_CONFIG_INT(ClWarningTeambalance, cl_warning_teambalance, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Warn about team balance")

MACRO_CONFIG_INT(ClMouseDeadzone, cl_mouse_deadzone, 300, 0, 0, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")
MACRO_CONFIG_INT(ClMouseFollowfactor, cl_mouse_followfactor, 60, 0, 200, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")
MACRO_CONFIG_INT(ClMouseMaxDistance, cl_mouse_max_distance, 800, 0, 0, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")

MACRO_CONFIG_INT(EdShowkeys, ed_showkeys, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")

//MACRO_CONFIG_INT(ClFlow, cl_flow, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")

MACRO_CONFIG_INT(ClShowWelcome, cl_show_welcome, 1, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")
MACRO_CONFIG_INT(ClMotdTime, cl_motd_time, 10, 0, 100, CFGFLAG_CLIENT|CFGFLAG_SAVE, "How long to show the server message of the day")

MACRO_CONFIG_STR(ClVersionServer, cl_version_server, 100, "version.teeworlds.com", CFGFLAG_CLIENT|CFGFLAG_SAVE, "Server to use to check for new versions")

MACRO_CONFIG_STR(ClLanguagefile, cl_languagefile, 255, "", CFGFLAG_CLIENT|CFGFLAG_SAVE, "What language file to use")

MACRO_CONFIG_INT(PlayerUseCustomColor, player_use_custom_color, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Toggles usage of custom colors")
MACRO_CONFIG_INT(PlayerColorBody, player_color_body, 65408, 0, 0xFFFFFF, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Player body color")
MACRO_CONFIG_INT(PlayerColorFeet, player_color_feet, 65408, 0, 0xFFFFFF, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Player feet color")
MACRO_CONFIG_STR(PlayerSkin, player_skin, 24, "default", CFGFLAG_CLIENT|CFGFLAG_SAVE, "Player skin")

MACRO_CONFIG_INT(UiPage, ui_page, 5, 0, 10, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Interface page")
MACRO_CONFIG_INT(UiToolboxPage, ui_toolbox_page, 0, 0, 2, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Toolbox page")
MACRO_CONFIG_STR(UiServerAddress, ui_server_address, 64, "localhost:8303", CFGFLAG_CLIENT|CFGFLAG_SAVE, "Interface server address")
MACRO_CONFIG_INT(UiScale, ui_scale, 100, 50, 150, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Interface scale")
MACRO_CONFIG_INT(UiMousesens, ui_mousesens, 100, 5, 100000, CFGFLAG_SAVE|CFGFLAG_CLIENT, "Mouse sensitivity for menus/editor")

MACRO_CONFIG_INT(UiColorHue, ui_color_hue, 160, 0, 255, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Interface color hue")
MACRO_CONFIG_INT(UiColorSat, ui_color_sat, 70, 0, 255, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Interface color saturation")
MACRO_CONFIG_INT(UiColorLht, ui_color_lht, 175, 0, 255, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Interface color lightness")
MACRO_CONFIG_INT(UiColorAlpha, ui_color_alpha, 228, 0, 255, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Interface alpha")

MACRO_CONFIG_INT(GfxNoclip, gfx_noclip, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "Disable clipping")

// server
MACRO_CONFIG_INT(SvWarmup, sv_warmup, 0, 0, 0, CFGFLAG_SERVER, "Number of seconds to do warmup before round starts")
MACRO_CONFIG_STR(SvMotd, sv_motd, 900, "", CFGFLAG_SERVER, "Message of the day to display for the clients")
MACRO_CONFIG_INT(SvTeamdamage, sv_teamdamage, 0, 0, 1, CFGFLAG_SERVER, "Team damage")
MACRO_CONFIG_STR(SvMaprotation, sv_maprotation, 768, "", CFGFLAG_SERVER, "Maps to rotate between")
MACRO_CONFIG_INT(SvRoundsPerMap, sv_rounds_per_map, 1, 1, 100, CFGFLAG_SERVER, "Number of rounds on each map before rotating")
MACRO_CONFIG_INT(SvPowerups, sv_powerups, 0, 0, 1, CFGFLAG_SERVER, "Allow powerups like ninja")
MACRO_CONFIG_INT(SvScorelimit, sv_scorelimit, 20, 0, 1000, CFGFLAG_SERVER, "Score limit (0 disables)")
MACRO_CONFIG_INT(SvTimelimit, sv_timelimit, 0, 0, 1000, CFGFLAG_SERVER, "Time limit in minutes (0 disables)")
MACRO_CONFIG_STR(SvGametype, sv_gametype, 32, "dm", CFGFLAG_SERVER, "Game type (dm, tdm, ctf)")
MACRO_CONFIG_INT(SvTournamentMode, sv_tournament_mode, 0, 0, 1, CFGFLAG_SERVER, "Tournament mode. When enabled, players joins the server as spectator")
MACRO_CONFIG_INT(SvSpamprotection, sv_spamprotection, 1, 0, 1, CFGFLAG_SERVER, "Spam protection")

MACRO_CONFIG_INT(SvRespawnDelayTDM, sv_respawn_delay_tdm, 3, 0, 10, CFGFLAG_SERVER, "Time needed to respawn after death in tdm gametype")

MACRO_CONFIG_INT(SvSpectatorSlots, sv_spectator_slots, 0, 0, MAX_CLIENTS, CFGFLAG_SERVER, "Number of slots to reserve for spectators")
MACRO_CONFIG_INT(SvTeambalanceTime, sv_teambalance_time, 1, 0, 1000, CFGFLAG_SERVER, "How many minutes to wait before autobalancing teams")
MACRO_CONFIG_INT(SvInactiveKickTime, sv_inactivekick_time, 3, 0, 1000, CFGFLAG_SERVER, "How many minutes to wait before taking care of inactive players")
MACRO_CONFIG_INT(SvInactiveKick, sv_inactivekick, 1, 0, 2, CFGFLAG_SERVER, "How to deal with inactive players (0=move to spectator, 1=move to free spectator slot/kick, 2=kick)")

MACRO_CONFIG_INT(SvStrictSpectateMode, sv_strict_spectate_mode, 0, 0, 1, CFGFLAG_SERVER, "Restricts information in spectator mode")
MACRO_CONFIG_INT(SvVoteSpectate, sv_vote_spectate, 1, 0, 1, CFGFLAG_SERVER, "Allow voting to move players to spectators")
MACRO_CONFIG_INT(SvVoteSpectateRejoindelay, sv_vote_spectate_rejoindelay, 3, 0, 1000, CFGFLAG_SERVER, "How many minutes to wait before a player can rejoin after being moved to spectators by vote")
MACRO_CONFIG_INT(SvVoteKick, sv_vote_kick, 1, 0, 1, CFGFLAG_SERVER, "Allow voting to kick players")
MACRO_CONFIG_INT(SvVoteKickMin, sv_vote_kick_min, 0, 0, MAX_CLIENTS, CFGFLAG_SERVER, "Minimum number of players required to start a kick vote")
MACRO_CONFIG_INT(SvVoteKickBantime, sv_vote_kick_bantime, 5, 0, 1440, CFGFLAG_SERVER, "The time to ban a player if kicked by vote. 0 makes it just use kick")

MACRO_CONFIG_INT(SvRegen, sv_regen, 0, 0, 50, CFGFLAG_SERVER, "Set regeneration")
MACRO_CONFIG_INT(SvStrip, sv_strip, 0, 0, 1, CFGFLAG_SERVER, "Enable or disable keeping weapon after teleporting")
MACRO_CONFIG_INT(SvInfiniteAmmo, sv_infinite_ammo, 0, 0, 1, CFGFLAG_SERVER, "Enable or disable infinite ammo")
MACRO_CONFIG_INT(SvTeleport, sv_teleport, 1, 0, 1, CFGFLAG_SERVER, "Enable or disable teleportation")
MACRO_CONFIG_INT(SvTeleportGrenade, sv_teleport_grenade, 1, 0, 1, CFGFLAG_SERVER, "Enable or disable teleport of grenade")
MACRO_CONFIG_INT(SvTeleportKill, sv_teleport_kill, 0, 0, 1, CFGFLAG_SERVER, "Teleporting one someone kills him")
MACRO_CONFIG_INT(SvTeleportVelReset, sv_teleport_vel_reset, 0, 0, 1, CFGFLAG_SERVER, "Reset velocity after teleport")
MACRO_CONFIG_INT(SvRocketJumpDamage, sv_rocket_jump_damage, 0, 0, 1, CFGFLAG_SERVER, "Enable or disable rocket jump damage")
MACRO_CONFIG_INT(SvPickupRespawn, sv_pickup_respawn, 1, -1, 120, CFGFLAG_SERVER, "Time before a pickup respawn")
MACRO_CONFIG_INT(SvSpeedupMult, sv_speedup_mult, 10, 1, 100, CFGFLAG_SERVER, "Boost power by multiplication")
MACRO_CONFIG_INT(SvSpeedupAdd, sv_speedup_add, 0, -100, 100, CFGFLAG_SERVER, "Boost power")
MACRO_CONFIG_INT(SvJumperAdd, sv_jumper_add, 0, -100, 100, CFGFLAG_SERVER, "Jumper power")
MACRO_CONFIG_INT(SvDoors, sv_doors, 1, 0, 1, CFGFLAG_SERVER, "Enable/Disable Doors")
MACRO_CONFIG_INT(SvLoadMapDefaults, sv_load_map_defaults, 1, 0, 1, CFGFLAG_SERVER, "Load map default settings")

MACRO_CONFIG_INT(SvZWarmup, sv_zwarmup, 15, 3, 60, CFGFLAG_SERVER, "Warmup time for choosing random zombie")
MACRO_CONFIG_INT(SvNukeTime, sv_nuke_time, 15, 1, 60, CFGFLAG_SERVER, "Time till nuke arrives")

MACRO_CONFIG_INT(SvDoor1OpenTime, sv_door1_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor2OpenTime, sv_door2_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor3OpenTime, sv_door3_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor4OpenTime, sv_door4_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor5OpenTime, sv_door5_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor6OpenTime, sv_door6_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor7OpenTime, sv_door7_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor8OpenTime, sv_door8_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor9OpenTime, sv_door9_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor10OpenTime, sv_door10_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor11OpenTime, sv_door11_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor12OpenTime, sv_door12_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor13OpenTime, sv_door13_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor14OpenTime, sv_door14_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor15OpenTime, sv_door15_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor16OpenTime, sv_door16_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor17OpenTime, sv_door17_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor18OpenTime, sv_door18_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor19OpenTime, sv_door19_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor20OpenTime, sv_door20_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor21OpenTime, sv_door21_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor22OpenTime, sv_door22_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor23OpenTime, sv_door23_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor24OpenTime, sv_door24_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor25OpenTime, sv_door25_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor26OpenTime, sv_door26_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor27OpenTime, sv_door27_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor28OpenTime, sv_door28_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor29OpenTime, sv_door29_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor30OpenTime, sv_door30_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor31OpenTime, sv_door31_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")
MACRO_CONFIG_INT(SvDoor32OpenTime, sv_door32_open_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door opens")

MACRO_CONFIG_INT(SvDoor1CloseTime, sv_door1_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor2CloseTime, sv_door2_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor3CloseTime, sv_door3_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor4CloseTime, sv_door4_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor5CloseTime, sv_door5_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor6CloseTime, sv_door6_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor7CloseTime, sv_door7_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor8CloseTime, sv_door8_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor9CloseTime, sv_door9_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor10CloseTime, sv_door10_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor11CloseTime, sv_door11_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor12CloseTime, sv_door12_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor13CloseTime, sv_door13_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor14CloseTime, sv_door14_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor15CloseTime, sv_door15_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor16CloseTime, sv_door16_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor17CloseTime, sv_door17_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor18CloseTime, sv_door18_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor19CloseTime, sv_door19_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor20CloseTime, sv_door20_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor21CloseTime, sv_door21_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor22CloseTime, sv_door22_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor23CloseTime, sv_door23_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor24CloseTime, sv_door24_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor25CloseTime, sv_door25_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor26CloseTime, sv_door26_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor27CloseTime, sv_door27_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor28CloseTime, sv_door28_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor29CloseTime, sv_door29_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor30CloseTime, sv_door30_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor31CloseTime, sv_door31_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")
MACRO_CONFIG_INT(SvDoor32CloseTime, sv_door32_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till door close for zombies")

MACRO_CONFIG_INT(SvDoor1ReopenTime, sv_door1_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor2ReopenTime, sv_door2_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor3ReopenTime, sv_door3_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor4ReopenTime, sv_door4_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor5ReopenTime, sv_door5_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor6ReopenTime, sv_door6_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor7ReopenTime, sv_door7_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor8ReopenTime, sv_door8_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor9ReopenTime, sv_door9_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor10ReopenTime, sv_door10_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor11ReopenTime, sv_door11_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor12ReopenTime, sv_door12_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor13ReopenTime, sv_door13_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor14ReopenTime, sv_door14_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor15ReopenTime, sv_door15_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor16ReopenTime, sv_door16_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor17ReopenTime, sv_door17_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor18ReopenTime, sv_door18_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor19ReopenTime, sv_door19_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor20ReopenTime, sv_door20_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor21ReopenTime, sv_door21_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor22ReopenTime, sv_door22_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor23ReopenTime, sv_door23_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor24ReopenTime, sv_door24_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor25ReopenTime, sv_door25_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor26ReopenTime, sv_door26_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor27ReopenTime, sv_door27_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor28ReopenTime, sv_door28_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor29ReopenTime, sv_door29_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor30ReopenTime, sv_door30_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor31ReopenTime, sv_door31_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")
MACRO_CONFIG_INT(SvDoor32ReopenTime, sv_door32_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till door reopens for zombies")

MACRO_CONFIG_INT(SvZDoor1CloseTime, sv_zdoor1_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor2CloseTime, sv_zdoor2_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor3CloseTime, sv_zdoor3_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor4CloseTime, sv_zdoor4_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor5CloseTime, sv_zdoor5_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor6CloseTime, sv_zdoor6_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor7CloseTime, sv_zdoor7_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor8CloseTime, sv_zdoor8_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor9CloseTime, sv_zdoor9_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor10CloseTime, sv_zdoor10_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor11CloseTime, sv_zdoor11_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor12CloseTime, sv_zdoor12_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor13CloseTime, sv_zdoor13_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor14CloseTime, sv_zdoor14_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor15CloseTime, sv_zdoor15_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")
MACRO_CONFIG_INT(SvZDoor16CloseTime, sv_zdoor16_close_time, 3, -1, 60, CFGFLAG_SERVER, "Time till zdoor close for zombies")

MACRO_CONFIG_INT(SvZDoor1ReopenTime, sv_zdoor1_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor2ReopenTime, sv_zdoor2_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor3ReopenTime, sv_zdoor3_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor4ReopenTime, sv_zdoor4_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor5ReopenTime, sv_zdoor5_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor6ReopenTime, sv_zdoor6_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor7ReopenTime, sv_zdoor7_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor8ReopenTime, sv_zdoor8_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor9ReopenTime, sv_zdoor9_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor10ReopenTime, sv_zdoor10_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor11ReopenTime, sv_zdoor11_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor12ReopenTime, sv_zdoor12_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor13ReopenTime, sv_zdoor13_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor14ReopenTime, sv_zdoor14_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor15ReopenTime, sv_zdoor15_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")
MACRO_CONFIG_INT(SvZDoor16ReopenTime, sv_zdoor16_reopen_time, 10, -1, 60, CFGFLAG_SERVER, "Time till zdoor reopens for zombies")



// debug
#ifdef CONF_DEBUG // this one can crash the server if not used correctly
	MACRO_CONFIG_INT(DbgDummies, dbg_dummies, 0, 0, 15, CFGFLAG_SERVER, "")
#endif

MACRO_CONFIG_INT(DbgFocus, dbg_focus, 0, 0, 1, CFGFLAG_CLIENT, "")
MACRO_CONFIG_INT(DbgTuning, dbg_tuning, 0, 0, 1, CFGFLAG_CLIENT, "")
#endif
